{% set name = "nionswift-eels-analysis" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f56f2e15b14533652ee57a0d8d6ab90f1851c4be9d31147db304481a3f7e5725

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - nionswift >=0.16.0,<0.17.0
    - nionui >=0.6.3,<0.7.0

test:
  imports:
    - nion.eels_analysis
    - nion.eels_analysis.test
    - nionswift_plugin.nion_eels_analysis
    - nionswift_plugin.nion_eels_analysis.test

about:
  home: https://github.com/nion-software/nionswift-usim
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A Nion Swift package to simulate a STEM microscope, scanner, and cameras
  dev_url: https://github.com/nion-software/nionswift-usim

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
