{% set python_min = "3.11" %}
{% set name = "nionswift-eels-analysis" %}
{% set version = "0.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: df34ef0aa50cd51931a623f06dda4b03587cefe809b8ae403d14c1798b15d090

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - nionswift >=16.15,<17.0
    - nionui >=10.0,<11.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - nion.eels_analysis
    - nion.eels_analysis.test
    - nionswift_plugin.nion_eels_analysis
    - nionswift_plugin.nion_eels_analysis.test

about:
  home: https://github.com/nion-software/nionswift-usim
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A Nion Swift package to simulate a STEM microscope, scanner, and cameras
  dev_url: https://github.com/nion-software/nionswift-usim

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
