{% set name = "nionswift-eels-analysis" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bf4eab3649b4b1992bd8af87cded75a2bc697ee3822c7f29fdb99c4ae5f169ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - nionswift >=16.9.0,<17.0.0
    - nionui >=7.0.0,<8.0.0

test:
  imports:
    - nion.eels_analysis
    - nion.eels_analysis.test
    - nionswift_plugin.nion_eels_analysis
    - nionswift_plugin.nion_eels_analysis.test

about:
  home: https://github.com/nion-software/nionswift-usim
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A Nion Swift package to simulate a STEM microscope, scanner, and cameras
  dev_url: https://github.com/nion-software/nionswift-usim

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
